# Generated by Django 5.2.4 on 2025-07-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome único para a categoria.', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional da categoria.', null=True)),
            ],
            options={
                'verbose_name': ('Categoria',),
                'verbose_name_plural': ('Categorias',),
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=255)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['nome_fantasia'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sku', models.CharField(help_text='SKU (Stock Keeping Unit) - Código de Barras ou código único do produto.', max_length=100, unique=True)),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unidade_medida', models.CharField(default='unidade', help_text='Ex: unidade, kg, litro, metro.', max_length=20)),
                ('unididade_minimo', models.PositiveIntegerField(default=0, help_text='Quantidade mínima em estoque para gerar um alerta.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizaçao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='core.fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
    ]
