# Generated by Django 5.2.4 on 2025-07-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade mínima em estoque para gerar um alerta.'),
        ),
    ]
